name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      SATELLITE_NAME: ${{ secrets.SATELLITE_NAME }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.12
      - uses: actions/checkout@v2
      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - name: Earthly version
        run: earthly --version
      - name: Run build conditionally
        run: |
          # Update the ALLOW variable with your list of allowed satellite users (Github usernames)
          # If a user does not match the list, the build will run without the satellite.
          ALLOW='ezeev,'
          echo $GITHUB_ACTOR
          if [[ $ALLOW =~ (^|,)$GITHUB_ACTOR($|,) ]]; then
            echo "$GITHUB_ACTOR is allowed. Running Earthly with Satellite."
            earthly --sat $SATELLITE_NAME +build
          else
            echo "$GITHUB_ACTOR not allowed. Running Earthly without Satellite."
            earthly +build
          fi
